apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
  selector:
    app: search-service